#!/bin/bash
#################################################################
# Written by Fabian Ihle, fabi@ihlecloud.de                     #
# Created: 22.03.2020                                           #
# github: https://github.com/n1tr0-5urf3r/icinga2-scripts       #
#                                                               #
# Displays information per jail                                 #
# Performance data for total blocked IPs                        #
# Shows which IP is banned until when                           # 
# ------------------------------------------------------------- #
# Changelog:                                                    #
# 020820 Version 1.01 - adapted to new fail2ban-client version  #
# 181121 Version 1.02 - use variables for binaries everywhere   #
# 160922 Version 1.03 - Shell check conformity                  #
# 130123 Version 1.04 - Some more output on erroneous permission#
#################################################################

# Helper message
print_help() {
        echo "
                Usage:

                        ./check_fail2ban -h Display this message
                                         -w <warning level> defaults to 10
                                         -c <crit level> defaults to 20
                                         -t Time: Display until when IPs will be banned
                                         -j <jaillist> i.e. comma separated string of jails, i.e. ssh,postfix
                                            Only check those jails
                Examples:
                        ./check_fail2ban -t -w 5 -c 10 -j ssh,postfix
                        ./check_fail2ban -t
        "
}

print_error() {
        echo -e "Error: $1\\n"
        exit 3
}

# Get binaries
FBIN=$(command -v fail2ban-client)
FBINSERVER=$(command -v fail2ban-server)
SUDO=$(command -v sudo)
if [ -z "$FBIN" ]; then
        print_error "fail2ban-client not found"
fi
if [ -z "$FBINSERVER" ]; then
        print_error "fail2ban-server not found"
fi
if [ -z "$SUDO" ]; then
        print_error "sudo not found. Please install it"
fi

# Check $SUDO permissions
VISUDO=$($SUDO -l -U nagios)
if echo "$VISUDO" | grep -q "(root) NOPASSWD: ${FBIN} status$" &&
   echo "$VISUDO" | grep -q "(root) NOPASSWD: ${FBIN} status \*$" &&
   echo "$VISUDO" | grep -q "(root) NOPASSWD: ${FBIN} get \* bantime$"; then
                :
else
                echo "Not all sudo permissions available! Please refer to documentation."
                echo "If you have set them up, make sure that the command 'sudo -u nagios /usr/lib/nagios/plugins/check_fail2ban -t -w 1 -c 2' correctly displays your jails."
                print_error "If they do not show up, try repairing sudo permissions with the command 'chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo'"
fi


# Parse Arguments
while test -n "$1"; do
    case "$1" in
        -c)
            CRIT=$2
            shift
            ;;
        -h)
            print_help
            exit 3
            ;;
        -w)
            WARN=$2
            shift
            ;;
        -t)
            TIME=true
            ;;
        -j)
            MANUAL=true
            JAILLIST=$2
            shift
            ;;
        *)
            print_help
            print_error "Unknown argument: $1"
            ;;
    esac
  shift
done

# Get List of Jails
if [ ! "$MANUAL" = true ]; then
        JAILLIST=$(${SUDO} "${FBIN}" status |grep "Jail list" | sed 's/`- Jail list://g' | sed 's/ //g')
fi

# check for running service
COLUMNS="" ps -aux | grep "${FBINSERVER}" | grep -v grep > /dev/null 2>&1
if [[ "$?" == "0" ]]; then
    echo "OK: fail2ban running"
else
    echo "CRIT: fail2ban NOT running"
    exit 2
fi

# Parse jaillist
IFS=',' read -ra JAILS <<< "$JAILLIST"
for JAIL in "${JAILS[@]}"; do

        if $SUDO "$FBIN" status "$JAIL" | grep -q "does not exist"; then
                print_error "Jail \"$JAIL\" not found"
        fi
        if [ "$TIME" = true ]; then
                # Time is currently not supported
                #BANNED_IPS=$($SUDO "$FBIN" get $JAIL banip --with-time| sed 's/ .*= / banned till /g')
                BANNED_IPS=$($SUDO "$FBIN" status "$JAIL" | grep "Banned IP list:" | sed 's/^.*Banned IP list://g')
        else
                BANNED_IPS=$($SUDO "$FBIN" status "$JAIL" | grep "Banned IP list:" | sed 's/^.*Banned IP list://g')
        fi

        # Get Amount of bans
        BANS=0
        BANS=$($SUDO "${FBIN}" status "$JAIL" | grep -o "Currently banned:.*" | sed 's/Currently banned://g')
        TOTALBANS=$((TOTALBANS+BANS))

        # Get Bantime for jail
        BANTIME=$($SUDO "$FBIN" get "$JAIL" bantime)

        # Assemble Output
        OUTPUT="$OUTPUT\\nJail: $JAIL\\nBan Time: $BANTIME\\nCurrently Banned: $BANS\\nBanned IPs: $BANNED_IPS\\n"
done

# Set default values
if [ -z "$CRIT" ]; then
        CRIT=20
fi

if [ -z "$WARN" ]; then
        WARN=10
fi

if [ $WARN -ge $CRIT ]; then
        print_error "Error: CRIT must be greater than WARN"
fi

# Append additional info
OUTPUT=$(echo -e "$OUTPUT\\nTotal banned: $TOTALBANS IPs|banned_IP=${TOTALBANS};${WARN};${CRIT}")

# States
if [ "$TOTALBANS" -ge ${WARN} ] && [ "$TOTALBANS" -lt ${CRIT} ]; then
        echo "WARNING:$OUTPUT"
        exit 1
elif [ "$TOTALBANS" -ge ${CRIT} ];then
        echo "CRITICAL:$OUTPUT"
        exit 2
else
        echo "$OUTPUT"
        exit 0
fi
